In [1]:
import numpy as np
a=np.array([4,5,6])
a

array([4, 5, 6])

In [5]:
b=np.array([(1.5,2,3),(4,5,6)],dtype=float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [6]:
a.sum()

15

In [7]:
b.sum()

21.5

In [8]:
a.min()

4

In [9]:
b.min()

1.5

In [10]:
b.max(axis=1)

array([3., 6.])

In [17]:
b.max()

6.0

In [20]:
b.cumsum(axis=0)

array([[1.5, 2. , 3. ],
       [5.5, 7. , 9. ]])

In [22]:
a.cumsum(axis=0)

array([ 4,  9, 15], dtype=int32)

In [23]:
b.cumsum(axis=1)

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [26]:
a.cumsum(axis=0)

array([ 4,  9, 15], dtype=int32)

In [27]:
a.mean()

5.0

In [28]:
b.mean()

3.5833333333333335

In [29]:
np.median(a)

5.0

np.median(b)

In [30]:
np.median(b)

3.5

In [31]:
np.std(b)

1.5920810978785667

In [32]:
np.std(a)

0.816496580927726

In [5]:
a=np.arange(0,5)
a

array([0, 1, 2, 3, 4])

In [6]:
b=np.arange(5,10)
b

array([5, 6, 7, 8, 9])

In [7]:
a+b

array([ 5,  7,  9, 11, 13])

In [8]:
res=[]
for i in range(len(a)):
    res.append(a[i] + b[i])
np.array(res)

array([ 5,  7,  9, 11, 13])

l1 = list(range(5))
l1

In [10]:
l1=list(range(5))
l1

[0, 1, 2, 3, 4]

In [11]:
l2=list(range(5,10))
l2

[5, 6, 7, 8, 9]

In [12]:
l1+l2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
A=np.array([
    [0,0,  0],
    [1, 1, 1],
    [2, 2, 2],
    [3, 3, 3]
])
A

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [14]:
A.shape

(4, 3)

In [15]:
b=np.array([[1, 2, 3]])
b

array([[1, 2, 3]])

In [16]:
b.shape

(1, 3)

In [17]:
A+b

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [19]:
a=np.arange(0,6)
a

array([0, 1, 2, 3, 4, 5])

In [20]:
a+10

array([10, 11, 12, 13, 14, 15])

In [21]:
[x+10 for x in a]

[10, 11, 12, 13, 14, 15]

In [27]:
l=list(range(5))
l

[0, 1, 2, 3, 4]

In [22]:
a-5

array([-5, -4, -3, -2, -1,  0])

In [30]:
a * 3

9

In [31]:
(a - a.mean()) / a.std()

AttributeError: 'int' object has no attribute 'mean'

In [32]:
a

3

In [33]:
a > 2

True

In [34]:
a==0

False

In [35]:
a>2

True

TypeError: unsupported operand type(s) for %: 'function' and 'int'

In [36]:
np.sum(a>2)

1

In [37]:
A = np.arange(1,10).reshape(3,3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
A+100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [46]:
a%2

TypeError: unsupported operand type(s) for %: 'function' and 'int'

In [39]:
x=lambda x:x**2
x(9)
    

81

In [40]:
a=lambda x,y:x+y
a(4,5)

9

In [41]:
b=lambda x:x[0]=='a'
b('apple')

True

In [42]:
b('banana')

False

In [43]:
b=lambda  x:"Even" if x%2==0 else "odd"
b(3)

'odd'

In [44]:
b(2)

'Even'

In [47]:
176
129
144

144

In [48]:
L=[1,2,3,4,5,6,7]
L

[1, 2, 3, 4, 5, 6, 7]

In [49]:
map(lambda x:x*2,L)


In [50]:
list(map(lambda x:x*2,L))

[2, 4, 6, 8, 10, 12, 14]

In [51]:
list(map(lambda x:x%2==0,L))

[False, True, False, True, False, True, False]

In [53]:
map(lambda student:student['name'],L)

In [54]:
list(map(lambda student:student,L))

[1, 2, 3, 4, 5, 6, 7]

In [55]:
students=[
  {
      "name":"jacob martin",
      "father name":"Ros Martin",
      "Address":"123  Hill Street",
  },{
      "name":"Angela Stevens",
      "father name":"Robert Stevens",
      "Address":"3 Upper Street London",
  },{
      "name":"Ricky  Smart",
      "father name":"William smart",
      "Address":"Unknown",
  }    
]
    

    


In [56]:
list(map(lambda student:student['name'],students))

['jacob martin', 'Angela Stevens', 'Ricky  Smart']

In [57]:
L

[1, 2, 3, 4, 5, 6, 7]

In [58]:
list(filter(lambda x:x>4,L))

[5, 6, 7]

In [59]:
fruits=['Apple','Orange','Mango','Guava']
list(filter(lambda fruit:'e' in fruit,fruits))

['Apple', 'Orange']

In [60]:
import functools
L

[1, 2, 3, 4, 5, 6, 7]

In [61]:
functools.reduce(lambda x,y:x+y,L)

28

In [62]:
L1=[12,34,56,11,21,58]
L1

[12, 34, 56, 11, 21, 58]

In [ ]:
functools.reduce[lambda]